baseURL = "https://icenacl.github.io/icexyz/" # <head> 里面的 baseurl 信息，填你的博客地址
title = "icexyz Blog" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "hugo-clarity" # 主题 (需要自己下载)

[menu]

[[menu.main]]
identifier = 'note'
name = 'PaperNote'
url = '/post/'
weight = -110

[[menu.main]]
name = 'getting started'
url = '/getting-started/'
weight = -100
 
[[menu.main]]
name = "Links"
identifier = "Links"
weight = -108

[[menu.main]]
parent = "Links"
name = "LinkedIn"
url = "https://www.linkedin.com/"

[[menu.main]]
parent = "Links"
name = "Twitter"
url = "https://twitter.com/"

[params]
  author="icexyz"

  mainSections = ['blog', 'docs']

  mobileNavigation = "left"

  numberOfTagsShown = 14

  codeLineNumbers = true

  figurePositionLabel="Figure"
